---
- name: Consul | Template out config
  template:
    src: "{{ consul_configuration_template_path }}"
    dest: "{{ consul_configdir }}/consul.json"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
  become: true

- name: Consul | Copy logrotate conf
  template:
    src: "{{ consul_logrotate_template_path }}"
    dest: /etc/logrotate.d/consul
    mode: 0644
  become: true

- name: Consul | Copy consul.service file
  template:
    src: "{{ consul_service_template_path }}"
    dest: /etc/systemd/system/consul.service
    trim_blocks: false
    mode: 0644
    owner: root
    group: root
  become: true
